# Generated by Django 2.2 on 2020-04-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_w',
            fields=[
                ('Car_w_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Car_w_wz', models.CharField(max_length=16)),
                ('Car_w_length', models.FloatField(max_length=16)),
                ('Car_w_status', models.BooleanField(default=True)),
            ],
        ),
    ]
