# Generated by Django 2.2 on 2020-04-27 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Car_w', '0001_initial'),
        ('inout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('In_time', models.DateTimeField(auto_now_add=True)),
                ('Out_time', models.DateTimeField(blank=True, null=True)),
                ('All_time', models.CharField(blank=True, max_length=16, null=True)),
                ('Cat_status', models.BooleanField(default=True)),
                ('P_Money', models.FloatField(blank=True, max_length=8, null=True)),
                ('P_price', models.FloatField(blank=True, default=1.5, max_length=8, null=True)),
                ('P_Car_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inout.Car')),
                ('P_Car_w_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car_w.Car_w')),
            ],
        ),
    ]
