# Generated by Django 2.2 on 2020-04-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0003_pritest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriTest',
        ),
    ]
