# Generated by Django 2.2 on 2020-04-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0005_auto_20200430_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='P_price',
            field=models.FloatField(blank=True, default=1.5, max_length=8, null=True),
        ),
    ]
