# Generated by Django 2.2 on 2020-04-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='mobile',
            field=models.CharField(default='', max_length=11),
        ),
    ]
